- name: Setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/webapp"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755

- name: Create docker-compose.yml file
  file:
    path: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch

- name: Deploy Docker Compose project for Wordpress/MySQL/Nginx (Let's Encrypt) containers
  template:
    src: docker-compose.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644

- name: Import dependencies
  file: 
    src: "{{ role_path }}/files/index.html.j2"
    dest: /home/{{ system_user }}/webapp/index.html
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: link
    mode: 0644

- name: Run docker-compose up
  command:
    cmd: "{{ compose_binary_dir }}/docker-compose -f docker-compose.yml up -d"
  args:
    chdir: "{{ compose_project_dir }}" 