- name: "Clean Folder"
  file:
    path: "/home/{{ system_user }}/webapp"
    state: absent

- name: Create webapp directory
  file:
    path: "/home/{{ system_user }}/webapp/"
    state: directory

- name: install git
  package:
    name: git
    state: present
        #when: ansible_distribution=="CentOS"

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/diranetafen/static-website-example.git 
    dest: "/home/{{ system_user }}/webapp/"

- name: Import dependencies
  template: 
    src: index.html.j2
    dest: "/home/{{ system_user }}/webapp/index.html"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644

- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd:{{ apache_version }}
    ports:
      - "80:80"
    recreate: yes
    volumes:
      - "/home/{{ system_user }}/webapp:/usr/local/apache2/htdocs/"