- name: Setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/webapp"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755

- name: install git
  package:
    name: git
    state: present
        #when: ansible_distribution=="CentOS"

- name: Clone a repo with separate git directory
  git:
    repo: https://github.com/diranetafen/static-website-example.git 
    dest: "{{ compose_project_dir }}/webapp"

- name: Import dependencies
  template: 
    src: index.html.j2
    dest: "/home/{{ system_user }}/index.html"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644

- name: Create Apache container
  docker_container:
    name: webapp
    image: httpd::{{ apache_version }}
    ports:
    - "80:80"
    recreate: yes
    volumes:
    - /home/{{ system_user }}/webapp:/usr/local/apache2/htdocs/